config/routes.rb
Rails.application.routes.draw do
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  namespace :admin do
    resources :users
  end

  root to: 'tasks#index'
  resources :tasks do
    post :confirm, action: :confirm_new, on: :new
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
    # 検証前の値を正規化
    # before_validation :set_nameless_name

    # バリデーション設定
    validates :name, presence: true, length: { maximum:30 }
    validate :check_name

    belongs_to :user

    scope :recent, -> { order(created_at: :desc) }
    
    private
    def check_name
        if name&.include?(',')
            errors.add(:name, 'にカンマを含めることはできません')
        end
    end

    # def set_nameless_name
    #     if name.blank?
    #         self.name = '名前なし'
    #     end
    # end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    has_many :tasks
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :require_admin

  def index
    @users=User.all
  end

  def show
    @user=User.find(params[:id])
  end
  
  # ====ユーザー新規作成====
  def new
    @user=User.new
  end

  def create
    @user=User.new(user_params)

    #DB保存
    if @user.save
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @user=User.find(params[:id])
  end

  def update
    @user=User.find(params[:id])

    if @user.update(user_params)
      redirect_to admin_user_url(@user), notice: "ユーザー「#{@user.name}」を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user=User.find(params[:id])
    @user.destroy
    redirect_to admin_users_url, notice: "ユーザー「#{@user.name}」を削除しました。"
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :admin, :password, :password_confirmation)
  end

  def require_admin
    redirect_to root_url unless current_user.admin?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # 全てのコントローラーからセッションに保管されているログイン情報を利用できるようにする
  helper_method :current_user
  before_action :login_required

  private

  def current_user
    # セッションにログイン情報がある場合、@current_userにユーザ情報を格納する
    if session[:user_id]
      @current_user = User.find_by(id: session[:user_id])
    end 
  end

  def login_required
    redirect_to login_url unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # ログイン画面はログインフィルターをスキップする
  skip_before_action :login_required

  def new
  end

  # ログイン機能
  def create
    # メールアドレスでユーザを検索する
    user = User.find_by(email: session_params[:email])
    # ユーザが見つかった場合はパスワードによる認証をUserモデルにhas_secure_passwordを記述した時に
    # 自動で追加された"authenticate"メソッドで行う
    if user&.authenticate(session_params[:password])
      # 認証ができた場合にセッションにuser_idを格納する
      session[:user_id] = user.id
      redirect_to root_path, notice: 'ログインしました。'
    else
      # 認証失敗した場合再度ログインページを表示
      render :new
    end
  end


  # ログアウト機能
  def destroy
    # セッション内の情報を全て削除する
    reset_session
    # ルートページに遷移
    redirect_to root_url, notice: 'ログアウトしました。'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  
  # ====タスク一覧====
  def index
    # ログインしているユーザーに紐づくTaskだけ表示する
    # @tasks = current_user.tasks.recent
    # 
    @q = current_user.tasks.ransack(params[:q])
    @tasks = @q.result(distinct: true).recent
  end

  # ====タスク詳細====
  def show
  end

  # ====タスク新規登録====
  def new
    @task = Task.new
  end

  def create
    # viewから渡されたパラメータでオブジェクトを生成
    # user_idを含めた状態でTaskデータを登録する
    @task = current_user.tasks.new(task_params)

    # 確認画面で'戻る'ボタンを押された場合
    if params[:back].present?
      # 新規登録画面へ遷移
      render :new
      # 処理を終了
      return
    end

    # DB保存(create)
    if @task.save
      # Flashメッセージを設定
      redirect_to @task, notice: "タスク 「#{@task.name}」を登録しました。"
    else
      # 失敗した場合に再度登録画面を呼び出す
      render :new
    end
  end

  # ====タスク登録確認画面====
  def confirm_new
    @task = current_user.tasks.new(task_params)
    render :new unless @task.valid?
  end

  # ====タスク編集====
  def edit
  end

  def update
    # DBから該当するデータを検索し、オブジェクトを生成
    @task = current_user.tasks.find(params[:id])
    # DB保存(create)
    @task.update!(task_params)
    # Flashメッセージを設定
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を更新しました。"
  end

  # ====タスク削除====
  def destroy
    # データ削除
    @task.destroy
    # Flashメッセージを設定
    redirect_to tasks_url, notice: "タスク「#{@task.name}」を削除しました。"
  end

  private

  def set_task
      # findメソッドを使用してタスク詳細を表示する為に必要なオブジェクトを取得する
      @task = current_user.tasks.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:name, :description)
  end
end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/admin/users/_form.html.erb
<%# エラーメッセージ出力 %>
<%if user.errors.present?%>
    <ul id="error_explanation">
        <%user.errors.full_messages.each do |message|%>
            <li><%=message%></li>
        <%end%>
    </ul>
<%end%>

<%# フォーム出力 %>
<%=form_with model: [:admin, user], local: true do |f|%>
    <div class="form-group mb-3">
        <%=f.label :name, '名前'%>
        <%=f.text_field :name, class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
        <%=f.label :email, 'メールアドレス'%>
        <%=f.text_field :email, class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
        <%=f.label :password, 'パスワード'%>
        <%=f.password_field :password, class: 'form-control'%>
    </div>
    <div class="form-group mb-3">
        <%=f.label :password_confirmation, 'パスワード(確認用)'%>
        <%=f.password_field :password_confirmation, class: 'form-control'%>
    </div>
    <div class="form-check mb-3">
        <%=f.label :admin, class: 'form-check-label' do%>
            <%=f.check_box :admin, class: 'form-check-input'%>
                |　管理者権限
        <%end%>
    </div>
    <%=f.submit '登録する', class: 'btn btn-primary'%>
<%end%>

app/views/admin/users/edit.html.erb
<h1>ユーザーの編集</h1>

<div class="nav justify-content-end">
    <%=link_to 'back page', admin_users_path, class: 'nav-link'%>
</div>

<%=render partial: 'form', locals: { user: @user } %>

app/views/admin/users/index.html.erb
<h1>ユーザー一覧</h1>

<div class="mt-3">
  <%=link_to '新規登録', new_admin_user_path, class: 'btn btn-primary'%>
</div>

<div class="mt-5">
  <table class="table table-hover">
    <thead class="thead-default">
      <tr>
        <th><%=User.human_attribute_name(:name)%></th>
        <th><%=User.human_attribute_name(:email)%></th>
        <th><%=User.human_attribute_name(:admin)%></th>
        <th><%=User.human_attribute_name(:created_at)%></th>
        <th><%=User.human_attribute_name(:updated_at)%></th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%@users.each do |user|%>
        <tr>
          <td><%=link_to user.name, [:admin, user]%></td>
          <td><%=user.email%></td>
          <td><%=user.created_at%></td>
          <td><%=user.updated_at%></td>
          <td>
            <%=link_to '編集', edit_admin_user_path(user), class: 'btn btn-primary mr-3'%>
            <%=link_to '削除', [:admin, user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？"}, class: 'btn btn-danger'%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/admin/users/new.html.erb
<h1>ユーザ登録</h1>

<div class="nav justify-content-end">
    <%=link_to 'back page', admin_users_path, class: 'nav-link'%>
</div>

<%= render partial: 'form', locals: { user: @user }%>

app/views/admin/users/show.html.erb
<h1>ユーザーの詳細</h1>

<div class="nav justiy-content-end">
    <%=link_to 'back page', admin_users_path, class: 'nav-link'%>
</div>

<table class="table table-hover">
    <tbody>
        <tr>
            <th><%=User.human_attribute_name(:id)%></th>
            <td><%=@user.id%></td>
        </tr>
        <tr>
            <th><%=User.human_attribute_name(:name)%></th>
            <td><%=@user.name%></td>
        </tr>
        <tr>
            <th><%=User.human_attribute_name(:email)%></th>
            <td><%=@user.email%></td>
        </tr>
        <tr>
            <th><%=User.human_attribute_name(:admin)%></th>
            <td><%=@user.admin? ? 'あり' : 'なし'%></td>
        </tr>
        <tr>
            <th><%=User.human_attribute_name(:created_at)%></th>
            <td><%=@user.created_at%></td>
        </tr>
        <tr>
            <th><%=User.human_attribute_name(:updated_at)%></th>
            <td><%=@user.updated_at%></td>
        </tr>
    </tbody>
</table>

<%=link_to '編集', edit_admin_user_path, class: 'btn btn-primary mr-3'%>
<%=link_to '削除', [:admin, @user], method: :delete, data: { confirm: "ユーザー「#{user.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="app-title navbar navbar-expand-md nav-bar-light bg-light">
      <div class="navbar-brand">
        To-Dos
      </div>
      <%# ログアウトの為のナビバーリンク %>
      <ul class="navbar-nav ml-auto">
        <%if current_user%>
          <li class="nav-item">
            <%=link_to 'タスク一覧', tasks_path, class: 'nav-link'%>
          </li>
          <%if current_user.admin%>
            <li class="nav-item">
              <%=link_to 'ユーザ一覧', admin_users_path, class: 'nav-link'%>
            </li>
          <%end%>
          <li class="nav-item">
            <%=link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link'%>
          </li>
        <%else%>
          <li class="nav-item">
            <%=link_to 'ログイン', login_path, class: 'nav-link'%>
          </li>  
        <%end%>
      </ul>
    </div>
    
    <%# flashメッセージがあれば出力 %>
    <div class="container">
      <% if flash[:notice]%>
        <div class="alert alert-success">
          <%=flash[:notice]%>
        </div>
      <%end%>
    </div>
    <div class="container">
      <%= yield %>
    </div>
    
  </body>
</html>

app/views/tasks/_form.html.erb
<%# エラーメッセージ出力 %>
<%if task.errors.present?%>
    <ul id="error_explanation">
        <%task.errors.full_messages.each do |message|%>
            <li><%=message%></li>
        <%end%>
    </ul>
<%end%>

<%# フォーム出力 %>
<%=form_with  model: task, local: true do |f|%>
    <div class="form-group">
        <%=f.label :name%>
        <%=f.text_field :name, class: 'form-control', id: 'task_name'%>
    </div>
    <div class="form-group">
        <%=f.label :description%>
        <%=f.text_area :description, rows: 5, class: 'form-control', id: 'task_description'%>
    </div>
    <%=f.submit nil, class: 'btn btn-primary'%>
<%end%>

app/views/tasks/confirm_new.html.erb
<h1>登録内容の確認</h1>

<%=form_with model: @task, local: true do |f|%>
  <table class="table table-hover">
    <tbody>
      <tr>
        <th><%=Task.human_attribute_name(:name)%></th>
        <td><%=@task.name%></td>
        <%=f.hidden_field :name%>
      </tr>
      <tr>
        <th><%= Task.human_attribute_name(:description) %></th>
        <td><%=simple_format(@task.description)%></td>
        <%=f.hidden_field :description%>
      </tr>
    </tbody>
  </table>
  <%=f.submit '戻る', name: 'back', class: 'btn btn-secondary mr-3'%>
  <%=f.submit '登録', class: 'btn btn-primary'%>
<%end%>

app/views/tasks/edit.html.erb
<h1>タスクの編集</h1>

<div class="nav justify-content-end">
    <%=link_to '一覧へ', tasks_path, class: 'nav-link'%>
</div>

<%=render partial: 'form', locals: {task: @task}%>

app/views/tasks/index.html.erb
<h1>タスク一覧</h1>

<%# 検索フォーム作成 %>
<%= search_form_for @q, class: 'mb-5' do |f|%>
  <%# 名称検索フォーム %>
  <div class="form-group row">
    <%= f.label :name_cont, '名称検索', class: 'col-sm-2 col-form-label'%>
    <div class="col-sm-10">
      <%= f.search_field :name_cont, class: 'form-control'%>
    </div>
  </div>
  <%# 検索ボタン %>
  <div class="form-group">
    <%= f.submit class: 'btn btn-outline-primary'%>
  </div>
<%end%>

<div class="mt-3">
  <%= link_to '新規作成', new_task_path, class: 'btn btn-outline-dark' %>
</div>

<div class="mt-5">
    <table class="table table-hover">
        <thead class="thead-default">
            <tr>
                <th><%=Task.human_attribute_name(:name)%></th>
                <th><%=Task.human_attribute_name(:created_at)%></th>
                <th></th>
                <th></th>
            </tr>
            <tbody>
                <%@tasks.each do |task|%>
                    <tr>
                        <td><%=link_to task.name, task%></td>
                        <td><%=task.created_at%></td>
                        <td><%=link_to '編集', edit_task_path(task), class: 'btn btn-primary mr-3'%></td>
                        <td><%=link_to '削除', task, method: :delete, data: { confirm: "タスク「#{task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'%></td>
                    </tr>
                <%end%>
            </tbody>
        </thead>
    </table>
</div>

app/views/tasks/new.html.erb
<h1>タスクの新規登録</h1>

<div class="nav justify-content-end">
    <%=link_to 'back page', tasks_path, class: 'navbar-brand'%>
</div>

<%# エラーメッセージ出力 %>
<%if @task.errors.present?%>
    <ul id="error_explanation">
        <%task.errors.full_messages.each do |message|%>
            <li><%=message%></li>
        <%end%>
    </ul>
<%end%>

<%# フォームの出力 %>
<%=form_with model: @task, local: true, url: confirm_new_task_path do |f|%>
  <div class="form-group">
    <%=f.label :name%>
    <%=f.text_field :name, class: 'form-control', id: 'task_name'%>
  </div>
  <div class="form-group">
    <%=f.label :description%>
    <%=f.text_area :description, row: 5, class: 'form-control', id: 'task_description'%>
  </div>
  <%=f.submit '確認', class: 'btn btn-primary'%>
<%end%>

app/views/tasks/show.html.erb
<h1>タスクの詳細</h1>
<div class="nav justify-content-end">
    <%=link_to '一覧へ', tasks_path, class: 'nav-link'%>
</div>
<table class="table table-hover">
    <tbody>
        <%# タスクID表示 %>
        <tr>
            <th><%=Task.human_attribute_name(:id)%></th>
            <td><%=@task.id%></td>
        </tr>
        <%# タスク名表示 %>
        <tr>
            <th><%=Task.human_attribute_name(:name)%></th>
            <td><%=@task.name%></td>
        </tr>
        <%# タスクの説明表示 %>
        <tr>
            <th><%=Task.human_attribute_name(:description)%></th>
            <td><%=auto_link(simple_format(h(@task.description), {}, sanitize: false, wrapper_tag: "div"))%></td>
        </tr>
        <%# タスク作成日時表示 %>
        <tr>
            <th><%=Task.human_attribute_name(:created_at)%></th>
            <td><%=@task.created_at%></td>
        </tr>
        <%# タスク更新日時表示 %>
        <tr>
            <th><%=Task.human_attribute_name(:updated_at)%></th>
            <td><%=@task.updated_at%></td>
        </tr>
    </tbody>
</table>
<%# 編集ボタン %>
<%=link_to '編集', edit_task_path, class: 'btn btn-primary mr-3'%>
<%# 削除ボタン %>
<%=link_to '削除', @task, method: :delete, data: { confirm: "タスク「#{@task.name}」を削除します。よろしいですか？" }, class: 'btn btn-danger'%>